# Generated by Django 5.0.6 on 2024-06-17 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_usuario_nome_usuario_sobrenome_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscricao',
            options={'verbose_name': 'Inscrito'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário'},
        ),
    ]
