# Generated by Django 5.0.6 on 2024-06-17 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_inscricao_options_alter_usuario_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='eventos_participantes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_autor', to=settings.AUTH_USER_MODEL),
        ),
    ]
